Add servers
Andre601/Discord-Links pull request #2
Opened 2020-05-12 22:49 UTC by matahombres

2020-05-12 22:51 UTC, Andre601 commented on docs/server/minecraft.md
> +#### :discord-verified: Pterodactyl
Just put this under the other servers.
I don't see any reason as to why there should be a separate category just for one type so far.

2020-05-12 22:55 UTC, Andre601 requested changes
Please use the same domain for invites, which is Discord.gg
Also try to order them alphabetically.

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/GzQf686
Please use discord.gg url
```suggestion
https://discord.gg/GzQf686
```

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/KxkjDVg
Please use discord.gg url
```suggestion
https://discord.gg/KxkjDVg
```

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/GtcdWFw
Please use discord.gg url
```suggestion
https://discord.gg/GtcdWFw
```

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/zMzXSgk
Please use discord.gg url
```suggestion
https://discord.gg/zMzXSgk
```

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/gnpVs5m
Please use discord.gg url
```suggestion
https://discord.gg/gnpVs5m
```

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/K3tqXfT
Please use discord.gg url
```suggestion
https://discord.gg/K3tqXfT
```

2020-05-12 22:55 UTC, Andre601 commented on docs/server/minecraft.md
> +https://discord.com/invite/pixelmon
Please use discord.gg url
```suggestion
https://discord.gg/pixelmon
```

2020-05-13 03:57 UTC, matahombres commented
I change

2020-05-13 09:19 UTC, Andre601 commented
Could you also change the order of the server to have it in alphabetical order?

2020-05-13 11:51 UTC, Andre601 commented
Closing this in favour of #3 
Thanks for your contributions tho. I added most servers to the above Pull Request.

2020-05-13 11:51 UTC, closed without merging